#!/bin/sh
mkdir -p ~/.config/tmux/cache
echo "daemon arrancado en $(date)" >> ~/.config/tmux/cache/tmux-network-debug.log
CACHE=~/.config/tmux/cache/network
TMP="${CACHE}.tmp"
while true; do
    ~/.config/tmux/state/network "$@" > "$TMP"
    mv "$TMP" "$CACHE"
    sleep 5
done