#!/bin/bash

COMPATIBLE=false

for arg in "$@"; do
    case "$arg" in
        --compatible) COMPATIBLE=true ;;
    esac
done

if $COMPATIBLE; then
    ON="SOUND ON"
    OFF="SOUND OFF"
else
    ON="🕪"
    OFF="🕨"
fi

status=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
volume=$(echo "$status" | awk '{print $2}')

case "$status" in
    *MUTED*)
        echo "$OFF"
        ;;
    "Volume: 0.00")
        echo "$OFF"
        ;;
    *)
        echo "$ON"
        ;;
esac
