# Tema: alto_contraste
# marco=MAGENTA(5) texto=WHITE(7) clima=GREEN(2) helpers=MAGENTA(5) nav=MAGENTA(5)
set -g status-style "bg=colour0,fg=colour7"
set -g status-left "#[fg=colour5,bold]|#[fg=default] #[underscore]#S#[nounderscore] #h #[fg=colour5]| "
set -g status-right "#(sh ~/.config/tmux/state/sound) #[fg=colour5,bold]|#[fg=default] #(cat ~/.config/tmux/cache/network 2>/dev/null || echo '?') #[fg=colour5,bold]|#[fg=default] #[fg=colour2]%a %d#[fg=default] %b, %H:%M #[fg=colour5]|"
set -g window-status-current-format "#[fg=colour5,bold][#[fg=default]#I:#W#[fg=colour5]]"
set -g message-style "bg=colour5,fg=colour7,bold"
set -g pane-active-border-style "fg=colour5,bold"
set -g pane-border-style "fg=colour7"