# Tema: flatline
# marco=CYAN(6) texto=WHITE(7) clima=RED(1) helpers=RED(1) nav=RED(1)
set -g status-style "bg=colour0,fg=colour7"
set -g status-left "#[fg=colour6,bold]|#[fg=default] #[underscore]#S#[nounderscore] #h #[fg=colour6]| "
set -g status-right "#(sh ~/.config/tmux/state/sound) #[fg=colour6,bold]|#[fg=default] #(cat ~/.config/tmux/cache/network 2>/dev/null || echo '?') #[fg=colour6,bold]|#[fg=default] #[fg=colour1]%a %d#[fg=default] %b, %H:%M #[fg=colour6]|"
set -g window-status-current-format "#[fg=colour6,bold][#[fg=default]#I:#W#[fg=colour6]]"
set -g message-style "bg=colour1,fg=colour7,bold"
set -g pane-active-border-style "fg=colour1,bold"
set -g pane-border-style "fg=colour7"