# Tema: mono
# marco=WHITE(7) texto=WHITE(7) clima=WHITE(7) helpers=WHITE(7) nav=WHITE(7)
set -g status-style "bg=colour0,fg=colour7"
set -g status-left "#[fg=colour7,bold]|#[fg=default] #[underscore]#S#[nounderscore] #h #[fg=colour7]| "
set -g status-right "#(sh ~/.config/tmux/state/sound) #[fg=colour7,bold]|#[fg=default] #(cat ~/.config/tmux/cache/network 2>/dev/null || echo '?') #[fg=colour7,bold]|#[fg=default] #[fg=colour7]%a %d#[fg=default] %b, %H:%M #[fg=colour7]|"
set -g window-status-current-format "#[fg=colour7,bold][#[fg=default]#I:#W#[fg=colour7]]"
set -g message-style "bg=colour7,fg=colour0,bold"
set -g pane-active-border-style "fg=colour7,bold"
set -g pane-border-style "fg=colour7"